'use strict';
const number = 9200;
const street = 'Irvine Center Drive';
const address = `${number} ${street}`;
console.log('LearningFuze:', address);
const firstName = 'Uzair';
const lastName = 'Ashraf';
const age = 25;
const bio = `My name is ${firstName} ${lastName} and I am ${age} years old.`;
console.log('Bio:', bio);
const fruit = 'apple';
const item = 'pen';
const templateFruit = `I have a ${fruit}`;
const templateItem = `I have a ${item}`;
const applePen = `${fruit} ${item}`;
console.log(templateFruit);
console.log(templateItem);
console.log(applePen);
