'use strict';
const width = 3;
const height = 4;
const area = width * height;
console.log('Area is:', area);
console.log('Type of area is:', typeof area);
const bill = 16.99;
const payment = 20;
const change = payment - bill;
console.log('Value of change is:', change);
console.log('Type of change is:', typeof change);
const quizzes = 75;
const midterm = 85;
const final = 80;
const grade = (quizzes + midterm + final) / 3;
console.log('Value of grade is:', grade);
console.log('Type of grade is:', typeof grade);
const firstName = 'Frank';
const lastName = 'Kang';
const fullName = firstName + ' ' + lastName;
console.log('Value of fullName is:', fullName);
console.log('Type of fullName is:', typeof fullName);
const pH = 9;
const isAcidic = pH < 7;
console.log('The value of isAcidic is:', isAcidic);
console.log('The type of isAcidic is:', typeof isAcidic);
const headCount = 299;
const isSparta = headCount === 300;
console.log('Value of isSparta is:', isSparta);
console.log('Type of isSparta is:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('Value of motto is:', motto);
console.log('Type of motto is:', typeof motto);
